apiVersion: batch/v1
kind: Job
metadata:
  name: beam-wordcount
spec:
  template:
    metadata:
      labels:
        app: beam-wordcount
    spec:
      containers:
        - name: beam-wordcount
          image: python-worker-harness:2.56.0
          command: ["python"]
          args:
            - "-m"
            - "apache_beam.examples.wordcount"
            - "--runner=FlinkRunner"
            - "--flink_master=beam-word-len-cluster-rest:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--input"
            - "/etc/ucf.conf"
            - "--output"
            - "/tmp/output"
      restartPolicy: Never
