FROM apache/beam_java11_sdk:2.56.0

ARG BEAM_VERSION
ENV BEAM_VERSION=${BEAM_VERSION:-2.56.0}
ENV REPO_BASE_URL=https://repo1.maven.org/maven2/org/apache/beam

COPY --from=apache/beam_flink1.16_job_server:2.56.0  \
  /opt/apache/beam/jars/beam-runners-flink-job-server.jar /opt/apache/beam/jars/beam-runners-flink-job-server.jar
RUN wget ${REPO_BASE_URL}/beam-sdks-java-io-expansion-service/${BEAM_VERSION}/beam-sdks-java-io-expansion-service-${BEAM_VERSION}.jar \
          --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-expansion-service.jar \
  && wget ${REPO_BASE_URL}/beam-sdks-java-io-kafka/${BEAM_VERSION}/beam-sdks-java-io-kafka-${BEAM_VERSION}.jar \
          --progress=bar:force:noscroll -O /opt/apache/beam/jars/beam-sdks-java-io-kafka.jar \
  && wget ${REPO_BASE_URL}/beam-sdks-java-extensions-schemaio-expansion-service/${BEAM_VERSION}/beam-sdks-java-extensions-schemaio-expansion-service-${BEAM_VERSION}.jar \
          --progress=bar:force:noscroll -P /opt/apache/beam/jars/beam-sdks-java-extensions-schemaio-expansion-service.jar
