apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: beam-word-len
spec:
  image: beam-python-example:1.17
  imagePullPolicy: Never
  flinkVersion: v1_17
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "10"
  serviceAccount: flink
  podTemplate:
    spec:
      containers:
        - name: flink-main-container
          env:
            - name: BOOTSTRAP_SERVERS
              value: demo-cluster-kafka-bootstrap:9092
            - name: INPUT_TOPIC
              value: input-topic
            - name: GROUP_ID
              value: beam-word-len
            - name: OUTPUT_TOPIC
              value: output-topic-beam
          volumeMounts:
            - mountPath: /opt/flink/log
              name: flink-logs
            - mountPath: /tmp/beam-artifact-staging
              name: flink-staging
      volumes:
        - name: flink-logs
          emptyDir: {}
        - name: flink-staging
          emptyDir: {}
  jobManager:
    resource:
      memory: "6144Mi"
      cpu: 3
  taskManager:
    replicas: 1
    resource:
      memory: "6144Mi"
      cpu: 3
  job:
    jarURI: local:///opt/apache/beam/jars/beam-runners-flink-job-server.jar
    entryClass: org.apache.beam.runners.flink.FlinkPortableClientEntryPoint
    args:
      - "--driver-cmd"
      - "python /opt/flink/usrlib/word_len.py --deploy"
    parallelism: 3
    upgradeMode: stateless
