apiVersion: batch/v1
kind: Job
metadata:
  name: word-count-job
spec:
  template:
    metadata:
      labels:
        app: word-count-job
    spec:
      containers:
        - name: word-count
          image: beam-python-harness:2.56.0
          command: ["python"]
          args:
            - "-m"
            - "word_count.run"
            - "--runner=FlinkRunner"
            - "--flink_master=word-count-cluster-rest:8081"
            - "--flink_submit_uber_jar"
            - "--environment_type=EXTERNAL"
            - "--environment_config=localhost:50000"
            - "--input"
            - "/opt/apache/beam/LICENSE"
            - "--output"
            - "/tmp/output"
      restartPolicy: Never
