version: "3.5"

services:
  jobmanager-beam:
    image: beam-python-example:1.17
    command: jobmanager
    container_name: jobmanager-beam
    ports:
      - "8081:8081"
    networks:
      - appnet
    environment:
      - BOOTSTRAP_SERVERS=kafka-0:9092
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-beam
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
    volumes:
      - ./beam:/tmp/beam
  taskmanager-beam:
    image: beam-python-example:1.17
    command: taskmanager
    container_name: taskmanager-beam
    networks:
      - appnet
    volumes:
      - flink_data_beam:/tmp/
      - ./beam:/tmp/beam
    environment:
      - BOOTSTRAP_SERVERS=kafka-0:9092
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-beam
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    depends_on:
      - jobmanager-beam
  jobmanager-flink:
    image: flink-python-example:1.17
    command: jobmanager
    container_name: jobmanager-flink
    ports:
      - "8082:8081"
    networks:
      - appnet
    environment:
      - BOOTSTRAP_SERVERS=kafka-0:9092
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-flink
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
        rest.flamegraph.enabled: true
        web.backpressure.refresh-interval: 10000
    volumes:
      - ./flink:/tmp/flink
  taskmanager-flink:
    image: flink-python-example:1.17
    command: taskmanager
    container_name: taskmanager-flink
    networks:
      - appnet
    volumes:
      - flink_data_flink:/tmp/
      - ./flink:/tmp/flink
    environment:
      - BOOTSTRAP_SERVERS=kafka-0:9092
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager-flink
        taskmanager.numberOfTaskSlots: 10
        state.backend: filesystem
        state.checkpoints.dir: file:///tmp/flink-checkpoints
        state.savepoints.dir: file:///tmp/flink-savepoints
        heartbeat.interval: 1000
        heartbeat.timeout: 5000
    depends_on:
      - jobmanager-flink
  zookeeper:
    image: bitnami/zookeeper:3.5
    container_name: zookeeper
    ports:
      - "2181"
    networks:
      - appnet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
  kafka-0:
    image: bitnami/kafka:2.8.1
    container_name: kafka-0
    expose:
      - 9092
    ports:
      - "29092:29092"
    networks:
      - appnet
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_BROKER_ID=0
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://kafka-0:9092,EXTERNAL://localhost:29092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_NUM_PARTITIONS=3
      - KAFKA_CFG_DEFAULT_REPLICATION_FACTOR=1
    volumes:
      - kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.1
    container_name: kafka-ui
    ports:
      - "8080:8080"
    networks:
      - appnet
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-0:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - zookeeper
      - kafka-0

networks:
  appnet:
    name: app-network

volumes:
  flink_data_beam:
    driver: local
    name: flink_data_beam
  flink_data_flink:
    driver: local
    name: flink_data_flink
  zookeeper_data:
    driver: local
    name: zookeeper_data
  kafka_0_data:
    driver: local
    name: kafka_0_data
