# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class RcpServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.resolve = channel.unary_unary(
                '/chapter3.RcpService/resolve',
                request_serializer=service__pb2.Request.SerializeToString,
                response_deserializer=service__pb2.Response.FromString,
                )
        self.resolveBatch = channel.unary_unary(
                '/chapter3.RcpService/resolveBatch',
                request_serializer=service__pb2.RequestList.SerializeToString,
                response_deserializer=service__pb2.ResponseList.FromString,
                )


class RcpServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def resolve(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def resolveBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RcpServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'resolve': grpc.unary_unary_rpc_method_handler(
                    servicer.resolve,
                    request_deserializer=service__pb2.Request.FromString,
                    response_serializer=service__pb2.Response.SerializeToString,
            ),
            'resolveBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.resolveBatch,
                    request_deserializer=service__pb2.RequestList.FromString,
                    response_serializer=service__pb2.ResponseList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chapter3.RcpService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RcpService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def resolve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chapter3.RcpService/resolve',
            service__pb2.Request.SerializeToString,
            service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def resolveBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/chapter3.RcpService/resolveBatch',
            service__pb2.RequestList.SerializeToString,
            service__pb2.ResponseList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
